repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: check-circular-imports
        name: Check for circular imports
        entry: python scripts/development/analyze_architecture.py
        language: python
        types: [python]
        require_serial: true
      - id: validate-kb
        name: Validate Knowledge Base
        entry: python scripts/development/validate_kb.py
        language: python
        types: [markdown]
        pass_filenames: false